// This file is not on TypeScript so that it's reused in the Node scripts

// hasImage: false 表示在 public/images/<code>.jpg 没有专属图片，前端会回落到 0.jpg
// messageI18n: 状态码的本地化名称表，键是 locale 代码，值是该语言下的状态码标题
//              在非英文版页面中显示于英文名下方

const statuses = {
  100: { code: 100, message: 'Continue', messageI18n: { 'zh-CN': '继续', ja: '継続' }, hasImage: true },
  101: { code: 101, message: 'Switching Protocols', messageI18n: { 'zh-CN': '切换协议', ja: 'プロトコル切替' }, hasImage: true },
  102: { code: 102, message: 'Processing', messageI18n: { 'zh-CN': '处理中', ja: '処理中' }, hasImage: true },
  103: { code: 103, message: 'Early Hints', messageI18n: { 'zh-CN': '早期提示', ja: '早期ヒント' }, hasImage: true },
  200: { code: 200, message: 'OK', messageI18n: { 'zh-CN': '成功', ja: '成功' }, hasImage: true },
  201: { code: 201, message: 'Created', messageI18n: { 'zh-CN': '已创建', ja: '作成完了' }, hasImage: true },
  202: { code: 202, message: 'Accepted', messageI18n: { 'zh-CN': '已接受', ja: '受理' }, hasImage: true },
  203: { code: 203, message: 'Non-Authoritative Information', messageI18n: { 'zh-CN': '非权威信息', ja: '非公式情報' }, hasImage: true },
  204: { code: 204, message: 'No Content', messageI18n: { 'zh-CN': '无内容', ja: 'コンテンツなし' }, hasImage: true },
  205: { code: 205, message: 'Reset Content', messageI18n: { 'zh-CN': '重置内容', ja: 'コンテンツをリセット' }, hasImage: true },
  206: { code: 206, message: 'Partial Content', messageI18n: { 'zh-CN': '部分内容', ja: '部分的なコンテンツ' }, hasImage: true },
  207: { code: 207, message: 'Multi-Status', messageI18n: { 'zh-CN': '多状态', ja: '複数のステータス' }, hasImage: true },
  208: { code: 208, message: 'Already Reported', messageI18n: { 'zh-CN': '已报告', ja: '既に報告済み' }, hasImage: true },
  214: { code: 214, message: 'Transformation Applied', messageI18n: { 'zh-CN': '已应用转换', ja: '変換が適用されました' }, hasImage: true },
  226: { code: 226, message: 'IM Used', messageI18n: { 'zh-CN': '已使用实例操作', ja: 'IM 使用' }, hasImage: true },
  300: { code: 300, message: 'Multiple Choices', messageI18n: { 'zh-CN': '多种选择', ja: '複数の選択肢' }, hasImage: true },
  301: { code: 301, message: 'Moved Permanently', messageI18n: { 'zh-CN': '永久移动', ja: '恒久的に移動' }, hasImage: true },
  302: { code: 302, message: 'Found', messageI18n: { 'zh-CN': '临时移动', ja: '発見' }, hasImage: true },
  303: { code: 303, message: 'See Other', messageI18n: { 'zh-CN': '查看其他', ja: '他を参照' }, hasImage: true },
  304: { code: 304, message: 'Not Modified', messageI18n: { 'zh-CN': '未修改', ja: '未更新' }, hasImage: true },
  305: { code: 305, message: 'Use Proxy', messageI18n: { 'zh-CN': '使用代理', ja: 'プロキシを使用' }, hasImage: true },
  307: { code: 307, message: 'Temporary Redirect', messageI18n: { 'zh-CN': '临时重定向', ja: '一時的リダイレクト' }, hasImage: true },
  308: { code: 308, message: 'Permanent Redirect', messageI18n: { 'zh-CN': '永久重定向', ja: '恒久的リダイレクト' }, hasImage: true },
  400: { code: 400, message: 'Bad Request', messageI18n: { 'zh-CN': '错误请求', ja: '不正なリクエスト' }, hasImage: true },
  401: { code: 401, message: 'Unauthorized', messageI18n: { 'zh-CN': '未授权', ja: '認証が必要' }, hasImage: true },
  402: { code: 402, message: 'Payment Required', messageI18n: { 'zh-CN': '需要付款', ja: '支払いが必要' }, hasImage: true },
  403: { code: 403, message: 'Forbidden', messageI18n: { 'zh-CN': '禁止访问', ja: 'アクセス禁止' }, hasImage: true },
  404: { code: 404, message: 'Not Found', messageI18n: { 'zh-CN': '未找到', ja: '見つかりません' }, hasImage: true },
  405: { code: 405, message: 'Method Not Allowed', messageI18n: { 'zh-CN': '方法不允许', ja: 'メソッド許可なし' }, hasImage: true },
  406: { code: 406, message: 'Not Acceptable', messageI18n: { 'zh-CN': '不可接受', ja: '受理不可' }, hasImage: true },
  407: { code: 407, message: 'Proxy Authentication Required', messageI18n: { 'zh-CN': '需要代理身份验证', ja: 'プロキシ認証が必要' }, hasImage: true },
  408: { code: 408, message: 'Request Timeout', messageI18n: { 'zh-CN': '请求超时', ja: 'リクエストタイムアウト' }, hasImage: true },
  409: { code: 409, message: 'Conflict', messageI18n: { 'zh-CN': '冲突', ja: '競合' }, hasImage: true },
  410: { code: 410, message: 'Gone', messageI18n: { 'zh-CN': '已删除', ja: '消失' }, hasImage: true },
  411: { code: 411, message: 'Length Required', messageI18n: { 'zh-CN': '需要内容长度', ja: '長さが必要' }, hasImage: true },
  412: { code: 412, message: 'Precondition Failed', messageI18n: { 'zh-CN': '前提条件失败', ja: '前提条件失敗' }, hasImage: true },
  413: { code: 413, message: 'Payload Too Large', messageI18n: { 'zh-CN': '请求体过大', ja: 'ペイロード過大' }, hasImage: true },
  414: { code: 414, message: 'Request-URI Too Long', messageI18n: { 'zh-CN': '请求 URI 过长', ja: 'リクエスト URI が長すぎる' }, hasImage: true },
  415: { code: 415, message: 'Unsupported Media Type', messageI18n: { 'zh-CN': '不支持的媒体类型', ja: 'サポートされていないメディア形式' }, hasImage: true },
  416: { code: 416, message: 'Request Range Not Satisfiable', messageI18n: { 'zh-CN': '请求范围不满足', ja: 'リクエストの範囲が不適切' }, hasImage: true },
  417: { code: 417, message: 'Expectation Failed', messageI18n: { 'zh-CN': '期望失败', ja: '期待値が満たされない' }, hasImage: true },
  418: { code: 418, message: 'I\'m a teapot', messageI18n: { 'zh-CN': '我是茶壶', ja: '私はティーポット' }, hasImage: true },
  419: { code: 419, message: 'Page Expired', messageI18n: { 'zh-CN': '页面已过期', ja: 'ページの有効期限切れ' }, hasImage: true },
  420: { code: 420, message: 'Enhance Your Calm', messageI18n: { 'zh-CN': '冷静一下', ja: '落ち着いて' }, hasImage: true },
  421: { code: 421, message: 'Misdirected Request', messageI18n: { 'zh-CN': '请求方向错误', ja: '誤誘導されたリクエスト' }, hasImage: true },
  422: { code: 422, message: 'Unprocessable Entity', messageI18n: { 'zh-CN': '无法处理的实体', ja: '処理できないエンティティ' }, hasImage: true },
  423: { code: 423, message: 'Locked', messageI18n: { 'zh-CN': '已锁定', ja: 'ロック済み' }, hasImage: true },
  424: { code: 424, message: 'Failed Dependency', messageI18n: { 'zh-CN': '依赖失败', ja: '依存関係の失敗' }, hasImage: true },
  425: { code: 425, message: 'Too Early', messageI18n: { 'zh-CN': '请求过早', ja: '時期尚早' }, hasImage: true },
  426: { code: 426, message: 'Upgrade Required', messageI18n: { 'zh-CN': '需要升级', ja: 'アップグレードが必要' }, hasImage: true },
  428: { code: 428, message: 'Precondition Required', messageI18n: { 'zh-CN': '需要前提条件', ja: '前提条件が必要' }, hasImage: true },
  429: { code: 429, message: 'Too Many Requests', messageI18n: { 'zh-CN': '请求过多', ja: 'リクエストが多すぎる' }, hasImage: true },
  431: { code: 431, message: 'Request Header Fields Too Large', messageI18n: { 'zh-CN': '请求头字段过大', ja: 'リクエストヘッダーが大きすぎる' }, hasImage: true },
  444: { code: 444, message: 'No Response', messageI18n: { 'zh-CN': '无响应', ja: '応答なし' }, hasImage: true },
  // Nginx
  494: { code: 494, message: 'Request Header Too Large', messageI18n: { 'zh-CN': '请求头过大', ja: 'リクエストヘッダーが大きすぎる' }, hasImage: false },
  450: { code: 450, message: 'Blocked by Windows Parental Controls', messageI18n: { 'zh-CN': '被 Windows 家长控制拦截', ja: 'Windows ペアレンタルコントロールによりブロック' }, hasImage: true },
  451: { code: 451, message: 'Unavailable For Legal Reasons', messageI18n: { 'zh-CN': '因法律原因不可用', ja: '法的理由により利用不可' }, hasImage: true },
  495: { code: 495, message: 'SSL Certificate Error', messageI18n: { 'zh-CN': 'SSL 证书错误', ja: 'SSL 証明書エラー' }, hasImage: true },
  496: { code: 496, message: 'SSL Certificate Required', messageI18n: { 'zh-CN': '需要 SSL 证书', ja: 'SSL 証明書が必要' }, hasImage: true },
  497: { code: 497, message: 'HTTP Request Sent to HTTPS Port', messageI18n: { 'zh-CN': 'HTTP 请求发送到 HTTPS 端口', ja: 'HTTPS ポートへの HTTP リクエスト' }, hasImage: true },
  498: { code: 498, message: 'Token expired/invalid', messageI18n: { 'zh-CN': '令牌已过期或无效', ja: 'トークンが期限切れまたは無効' }, hasImage: true },
  499: { code: 499, message: 'Client Closed Request', messageI18n: { 'zh-CN': '客户端关闭请求', ja: 'クライアントがリクエストを終了' }, hasImage: true },
  500: { code: 500, message: 'Internal Server Error', messageI18n: { 'zh-CN': '服务器内部错误', ja: 'サーバー内部エラー' }, hasImage: true },
  501: { code: 501, message: 'Not Implemented', messageI18n: { 'zh-CN': '未实现', ja: '未実装' }, hasImage: true },
  502: { code: 502, message: 'Bad Gateway', messageI18n: { 'zh-CN': '网关错误', ja: '不正なゲートウェイ' }, hasImage: true },
  503: { code: 503, message: 'Service Unavailable', messageI18n: { 'zh-CN': '服务不可用', ja: 'サービス利用不可' }, hasImage: true },
  504: { code: 504, message: 'Gateway Timeout', messageI18n: { 'zh-CN': '网关超时', ja: 'ゲートウェイタイムアウト' }, hasImage: true },
  // 标准但之前缺失
  505: { code: 505, message: 'HTTP Version Not Supported', messageI18n: { 'zh-CN': '不支持的 HTTP 版本', ja: 'サポートされていない HTTP バージョン' }, hasImage: false },
  506: { code: 506, message: 'Variant Also Negotiates', messageI18n: { 'zh-CN': '变体也在协商', ja: 'バリアントも交渉対象' }, hasImage: true },
  507: { code: 507, message: 'Insufficient Storage', messageI18n: { 'zh-CN': '存储空间不足', ja: 'ストレージ不足' }, hasImage: true },
  508: { code: 508, message: 'Loop Detected', messageI18n: { 'zh-CN': '检测到循环', ja: 'ループ検出' }, hasImage: true },
  509: { code: 509, message: 'Bandwidth Limit Exceeded', messageI18n: { 'zh-CN': '超出带宽限制', ja: '帯域制限超過' }, hasImage: true },
  510: { code: 510, message: 'Not Extended', messageI18n: { 'zh-CN': '未扩展', ja: '拡張されていない' }, hasImage: true },
  511: { code: 511, message: 'Network Authentication Required', messageI18n: { 'zh-CN': '需要网络身份验证', ja: 'ネットワーク認証が必要' }, hasImage: true },
  // Cloudflare 5xx 系列
  520: { code: 520, message: 'Web Server Returned an Unknown Error', messageI18n: { 'zh-CN': 'Web 服务器返回未知错误', ja: 'Web サーバーが不明なエラーを返した' }, hasImage: false },
  521: { code: 521, message: 'Web Server Is Down', messageI18n: { 'zh-CN': 'Web 服务器宕机', ja: 'Web サーバーがダウンしています' }, hasImage: true },
  522: { code: 522, message: 'Connection Timed Out', messageI18n: { 'zh-CN': '连接超时', ja: '接続タイムアウト' }, hasImage: true },
  523: { code: 523, message: 'Origin Is Unreachable', messageI18n: { 'zh-CN': '源站不可达', ja: 'オリジンに到達できません' }, hasImage: true },
  524: { code: 524, message: 'A Timeout Occurred', messageI18n: { 'zh-CN': '发生超时', ja: 'タイムアウトが発生しました' }, hasImage: false },
  525: { code: 525, message: 'SSL Handshake Failed', messageI18n: { 'zh-CN': 'SSL 握手失败', ja: 'SSL ハンドシェイク失敗' }, hasImage: true },
  526: { code: 526, message: 'Invalid SSL Certificate', messageI18n: { 'zh-CN': 'SSL 证书无效', ja: '無効な SSL 証明書' }, hasImage: false },
  527: { code: 527, message: 'Railgun Error', messageI18n: { 'zh-CN': 'Railgun 错误', ja: 'Railgun エラー' }, hasImage: false },
  530: { code: 530, message: 'Site Frozen', messageI18n: { 'zh-CN': '站点已冻结', ja: 'サイト凍結' }, hasImage: true },
  599: { code: 599, message: 'Network Connect Timeout Error', messageI18n: { 'zh-CN': '网络连接超时错误', ja: 'ネットワーク接続タイムアウトエラー' }, hasImage: true },
  // Cloudflare 1xxx 系列
  1000: { code: 1000, message: 'DNS points to prohibited IP', messageI18n: { 'zh-CN': 'DNS 指向禁止的 IP', ja: 'DNS が禁止された IP を指している' }, hasImage: false },
  1001: { code: 1001, message: 'DNS resolution error', messageI18n: { 'zh-CN': 'DNS 解析错误', ja: 'DNS 解決エラー' }, hasImage: false },
  1002: { code: 1002, message: 'DNS points to prohibited IP', messageI18n: { 'zh-CN': 'DNS 指向禁止的 IP', ja: 'DNS が禁止された IP を指している' }, hasImage: false },
  1003: { code: 1003, message: 'Direct IP access not allowed', messageI18n: { 'zh-CN': '不允许直接 IP 访问', ja: '直接 IP アクセスは許可されていません' }, hasImage: false },
  1004: { code: 1004, message: 'Host not configured to serve web traffic', messageI18n: { 'zh-CN': '主机未配置为提供 Web 流量', ja: 'ホストは Web トラフィックを処理するように設定されていません' }, hasImage: false },
  1005: { code: 1005, message: 'Access Denied (IP banned by origin)', messageI18n: { 'zh-CN': '访问被拒绝（IP 被源站封禁）', ja: 'アクセス拒否（オリジンによる IP ブロック）' }, hasImage: false },
  1006: { code: 1006, message: 'Access Denied (IP banned)', messageI18n: { 'zh-CN': '访问被拒绝（IP 已封禁）', ja: 'アクセス拒否（IP ブロック）' }, hasImage: false },
  1007: { code: 1007, message: 'Access Denied (Self-signed SSL prohibited)', messageI18n: { 'zh-CN': '访问被拒绝（禁止自签名 SSL）', ja: 'アクセス拒否（自己署名 SSL 禁止）' }, hasImage: false },
  1008: { code: 1008, message: 'Access Denied (ASN banned)', messageI18n: { 'zh-CN': '访问被拒绝（ASN 已封禁）', ja: 'アクセス拒否（ASN ブロック）' }, hasImage: false },
  1010: { code: 1010, message: 'Access denied: Browser threat score too high', messageI18n: { 'zh-CN': '访问被拒绝：浏览器威胁评分过高', ja: 'アクセス拒否：ブラウザの脅威スコアが高すぎる' }, hasImage: false },
  1011: { code: 1011, message: 'Access denied (Hotlink protection)', messageI18n: { 'zh-CN': '访问被拒绝（防盗链保护）', ja: 'アクセス拒否（ホットリンク保護）' }, hasImage: false },
  1012: { code: 1012, message: 'Access denied (Cloudflare app blocked)', messageI18n: { 'zh-CN': '访问被拒绝（Cloudflare 应用拦截）', ja: 'アクセス拒否（Cloudflare アプリによるブロック）' }, hasImage: false },
  1013: { code: 1013, message: 'HTTP hostname and TLS SNI hostname mismatch', messageI18n: { 'zh-CN': 'HTTP 主机名与 TLS SNI 主机名不匹配', ja: 'HTTP ホスト名と TLS SNI ホスト名の不一致' }, hasImage: false },
  1014: { code: 1014, message: 'CNAME cross-user banned', messageI18n: { 'zh-CN': 'CNAME 跨用户已封禁', ja: 'CNAME クロスユーザーブロック' }, hasImage: false },
  1015: { code: 1015, message: 'You are being rate limited', messageI18n: { 'zh-CN': '您正在被限速', ja: 'レート制限中' }, hasImage: false },
  1016: { code: 1016, message: 'Origin DNS error', messageI18n: { 'zh-CN': '源站 DNS 错误', ja: 'オリジン DNS エラー' }, hasImage: false },
  1018: { code: 1018, message: 'Cannot find domain\'s settings', messageI18n: { 'zh-CN': '找不到域名设置', ja: 'ドメイン設定が見つかりません' }, hasImage: false },
  1019: { code: 1019, message: 'Compute server error (Worker recursive call)', messageI18n: { 'zh-CN': '计算服务器错误（Worker 递归调用）', ja: 'コンピュートサーバーエラー（Worker の再帰呼び出し）' }, hasImage: false },
  1020: { code: 1020, message: 'Access denied (Cloudflare Firewall Rule)', messageI18n: { 'zh-CN': '访问被拒绝（Cloudflare 防火墙规则）', ja: 'アクセス拒否（Cloudflare ファイアウォールルール）' }, hasImage: false },
  1023: { code: 1023, message: 'Host not configured (Page Rules)', messageI18n: { 'zh-CN': '主机未配置（页面规则）', ja: 'ホスト未設定（ページルール）' }, hasImage: false },
  1025: { code: 1025, message: 'Plan limit exceeded', messageI18n: { 'zh-CN': '超出套餐限制', ja: 'プラン制限超過' }, hasImage: false },
  1027: { code: 1027, message: 'Account suspended', messageI18n: { 'zh-CN': '账户已暂停', ja: 'アカウント停止' }, hasImage: false },
  1033: { code: 1033, message: 'Argo Tunnel error: connection unavailable', messageI18n: { 'zh-CN': 'Argo 隧道错误：连接不可用', ja: 'Argo Tunnel エラー：接続が利用できません' }, hasImage: false },
  1034: { code: 1034, message: 'Edge IP restricted', messageI18n: { 'zh-CN': '边缘 IP 受限', ja: 'エッジ IP 制限' }, hasImage: false },
  1035: { code: 1035, message: 'Invalid request rewrite (invalid URI path)', messageI18n: { 'zh-CN': '无效的请求重写（URI 路径无效）', ja: '無効なリクエスト書き換え（URI パスが無効）' }, hasImage: false },
  1036: { code: 1036, message: 'Invalid request rewrite (max length exceeded)', messageI18n: { 'zh-CN': '无效的请求重写（超出最大长度）', ja: '無効なリクエスト書き換え（最大長超過）' }, hasImage: false },
  1037: { code: 1037, message: 'Invalid request rewrite (invalid header name)', messageI18n: { 'zh-CN': '无效的请求重写（头名称无效）', ja: '無効なリクエスト書き換え（ヘッダー名が無効）' }, hasImage: false },
  1040: { code: 1040, message: 'Invalid request rewrite (transformations disabled)', messageI18n: { 'zh-CN': '无效的请求重写（转换已禁用）', ja: '無効なリクエスト書き換え（変換が無効）' }, hasImage: false },
  1041: { code: 1041, message: 'Invalid request rewrite (header modification rejected)', messageI18n: { 'zh-CN': '无效的请求重写（头修改被拒绝）', ja: '無効なリクエスト書き換え（ヘッダー変更が拒否）' }, hasImage: false },
  1101: { code: 1101, message: 'Worker threw a JavaScript exception', messageI18n: { 'zh-CN': 'Worker 抛出 JavaScript 异常', ja: 'Worker が JavaScript 例外をスロー' }, hasImage: false },
  1102: { code: 1102, message: 'Worker exceeded CPU time limit', messageI18n: { 'zh-CN': 'Worker 超出 CPU 时间限制', ja: 'Worker が CPU 時間制限を超過' }, hasImage: false },
  1104: { code: 1104, message: 'Email Address Obfuscation cannot be processed', messageI18n: { 'zh-CN': '邮件地址混淆无法处理', ja: 'メールアドレス難読化の処理失敗' }, hasImage: false },
  1105: { code: 1105, message: 'Rocket Loader exception', messageI18n: { 'zh-CN': 'Rocket Loader 异常', ja: 'Rocket Loader 例外' }, hasImage: false },
  1106: { code: 1106, message: 'Mirage exception', messageI18n: { 'zh-CN': 'Mirage 异常', ja: 'Mirage 例外' }, hasImage: false },
  1200: { code: 1200, message: 'Cache connection limit reached', messageI18n: { 'zh-CN': '缓存连接数已达上限', ja: 'キャッシュ接続数上限到達' }, hasImage: false },
  1201: { code: 1201, message: 'Origin returned malformed HTTP', messageI18n: { 'zh-CN': '源站返回了格式错误的 HTTP', ja: 'オリジンが不正な HTTP を返した' }, hasImage: false },
}

module.exports = statuses;
