// This file is not on TypeScript so that it's reused in the Node scripts

// hasImage: false 表示在 public/images/<code>.jpg 没有专属图片,前端会回落到 0.jpg

const statuses = {
  100: { code: 100, message: 'Continue', hasImage: true },
  101: { code: 101, message: 'Switching Protocols', hasImage: true },
  102: { code: 102, message: 'Processing', hasImage: true },
  103: { code: 103, message: 'Early Hints', hasImage: true },
  200: { code: 200, message: 'OK', hasImage: true },
  201: { code: 201, message: 'Created', hasImage: true },
  202: { code: 202, message: 'Accepted', hasImage: true },
  203: { code: 203, message: 'Non-Authoritative Information', hasImage: true },
  204: { code: 204, message: 'No Content', hasImage: true },
  205: { code: 205, message: 'Reset Content', hasImage: true },
  206: { code: 206, message: 'Partial Content', hasImage: true },
  207: { code: 207, message: 'Multi-Status', hasImage: true },
  208: { code: 208, message: 'Already Reported', hasImage: true },
  214: { code: 214, message: 'Transformation Applied', hasImage: true },
  226: { code: 226, message: 'IM Used', hasImage: true },
  300: { code: 300, message: 'Multiple Choices', hasImage: true },
  301: { code: 301, message: 'Moved Permanently', hasImage: true },
  302: { code: 302, message: 'Found', hasImage: true },
  303: { code: 303, message: 'See Other', hasImage: true },
  304: { code: 304, message: 'Not Modified', hasImage: true },
  305: { code: 305, message: 'Use Proxy', hasImage: true },
  307: { code: 307, message: 'Temporary Redirect', hasImage: true },
  308: { code: 308, message: 'Permanent Redirect', hasImage: true },
  400: { code: 400, message: 'Bad Request', hasImage: true },
  401: { code: 401, message: 'Unauthorized', hasImage: true },
  402: { code: 402, message: 'Payment Required', hasImage: true },
  403: { code: 403, message: 'Forbidden', hasImage: true },
  404: { code: 404, message: 'Not Found', hasImage: true },
  405: { code: 405, message: 'Method Not Allowed', hasImage: true },
  406: { code: 406, message: 'Not Acceptable', hasImage: true },
  407: { code: 407, message: 'Proxy Authentication Required', hasImage: true },
  408: { code: 408, message: 'Request Timeout', hasImage: true },
  409: { code: 409, message: 'Conflict', hasImage: true },
  410: { code: 410, message: 'Gone', hasImage: true },
  411: { code: 411, message: 'Length Required', hasImage: true },
  412: { code: 412, message: 'Precondition Failed', hasImage: true },
  413: { code: 413, message: 'Payload Too Large', hasImage: true },
  414: { code: 414, message: 'Request-URI Too Long', hasImage: true },
  415: { code: 415, message: 'Unsupported Media Type', hasImage: true },
  416: { code: 416, message: 'Request Range Not Satisfiable', hasImage: true },
  417: { code: 417, message: 'Expectation Failed', hasImage: true },
  418: { code: 418, message: 'I’m a teapot', hasImage: true },
  419: { code: 419, message: 'Page Expired', hasImage: true },
  420: { code: 420, message: 'Enhance Your Calm', hasImage: true },
  421: { code: 421, message: 'Misdirected Request', hasImage: true },
  422: { code: 422, message: 'Unprocessable Entity', hasImage: true },
  423: { code: 423, message: 'Locked', hasImage: true },
  424: { code: 424, message: 'Failed Dependency', hasImage: true },
  425: { code: 425, message: 'Too Early', hasImage: true },
  426: { code: 426, message: 'Upgrade Required', hasImage: true },
  428: { code: 428, message: 'Precondition Required', hasImage: true },
  429: { code: 429, message: 'Too Many Requests', hasImage: true },
  431: { code: 431, message: 'Request Header Fields Too Large', hasImage: true },
  444: { code: 444, message: 'No Response', hasImage: true },
  // Nginx
  494: { code: 494, message: 'Request Header Too Large', hasImage: false },
  450: { code: 450, message: 'Blocked by Windows Parental Controls', hasImage: true },
  451: { code: 451, message: 'Unavailable For Legal Reasons', hasImage: true },
  495: { code: 495, message: 'SSL Certificate Error', hasImage: true },
  496: { code: 496, message: 'SSL Certificate Required', hasImage: true },
  497: { code: 497, message: 'HTTP Request Sent to HTTPS Port', hasImage: true },
  498: { code: 498, message: 'Token expired/invalid', hasImage: true },
  499: { code: 499, message: 'Client Closed Request', hasImage: true },
  500: { code: 500, message: 'Internal Server Error', hasImage: true },
  501: { code: 501, message: 'Not Implemented', hasImage: true },
  502: { code: 502, message: 'Bad Gateway', hasImage: true },
  503: { code: 503, message: 'Service Unavailable', hasImage: true },
  504: { code: 504, message: 'Gateway Timeout', hasImage: true },
  // 标准但之前缺失
  505: { code: 505, message: 'HTTP Version Not Supported', hasImage: false },
  506: { code: 506, message: 'Variant Also Negotiates', hasImage: true },
  507: { code: 507, message: 'Insufficient Storage', hasImage: true },
  508: { code: 508, message: 'Loop Detected', hasImage: true },
  509: { code: 509, message: 'Bandwidth Limit Exceeded', hasImage: true },
  510: { code: 510, message: 'Not Extended', hasImage: true },
  511: { code: 511, message: 'Network Authentication Required', hasImage: true },
  // Cloudflare 5xx 系列(522 / 523 / 525 / 530 已存在)
  520: { code: 520, message: 'Web Server Returned an Unknown Error', hasImage: false },
  521: { code: 521, message: 'Web Server Is Down', hasImage: true },
  522: { code: 522, message: 'Connection Timed Out', hasImage: true },
  523: { code: 523, message: 'Origin Is Unreachable', hasImage: true },
  524: { code: 524, message: 'A Timeout Occurred', hasImage: false },
  525: { code: 525, message: 'SSL Handshake Failed', hasImage: true },
  526: { code: 526, message: 'Invalid SSL Certificate', hasImage: false },
  527: { code: 527, message: 'Railgun Error', hasImage: false },
  530: { code: 530, message: 'Site Frozen', hasImage: true },
  599: { code: 599, message: 'Network Connect Timeout Error', hasImage: true },
  // Cloudflare 1xxx 系列 - 全部为非官方,无图片
  1000: { code: 1000, message: 'DNS points to prohibited IP', hasImage: false },
  1001: { code: 1001, message: 'DNS resolution error', hasImage: false },
  1002: { code: 1002, message: 'DNS points to prohibited IP', hasImage: false },
  1003: { code: 1003, message: 'Direct IP access not allowed', hasImage: false },
  1004: { code: 1004, message: 'Host not configured to serve web traffic', hasImage: false },
  1005: { code: 1005, message: 'Access Denied (IP banned by origin)', hasImage: false },
  1006: { code: 1006, message: 'Access Denied (IP banned)', hasImage: false },
  1007: { code: 1007, message: 'Access Denied (Self-signed SSL prohibited)', hasImage: false },
  1008: { code: 1008, message: 'Access Denied (ASN banned)', hasImage: false },
  1010: { code: 1010, message: 'Access denied: Browser threat score too high', hasImage: false },
  1011: { code: 1011, message: 'Access denied (Hotlink protection)', hasImage: false },
  1012: { code: 1012, message: 'Access denied (Cloudflare app blocked)', hasImage: false },
  1013: { code: 1013, message: 'HTTP hostname and TLS SNI hostname mismatch', hasImage: false },
  1014: { code: 1014, message: 'CNAME cross-user banned', hasImage: false },
  1015: { code: 1015, message: 'You are being rate limited', hasImage: false },
  1016: { code: 1016, message: 'Origin DNS error', hasImage: false },
  1018: { code: 1018, message: 'Cannot find domain’s settings', hasImage: false },
  1019: { code: 1019, message: 'Compute server error (Worker recursive call)', hasImage: false },
  1020: { code: 1020, message: 'Access denied (Cloudflare Firewall Rule)', hasImage: false },
  1023: { code: 1023, message: 'Host not configured (Page Rules)', hasImage: false },
  1025: { code: 1025, message: 'Plan limit exceeded', hasImage: false },
  1027: { code: 1027, message: 'Account suspended', hasImage: false },
  1033: { code: 1033, message: 'Argo Tunnel error: connection unavailable', hasImage: false },
  1034: { code: 1034, message: 'Edge IP restricted', hasImage: false },
  1035: { code: 1035, message: 'Invalid request rewrite (invalid URI path)', hasImage: false },
  1036: { code: 1036, message: 'Invalid request rewrite (max length exceeded)', hasImage: false },
  1037: { code: 1037, message: 'Invalid request rewrite (invalid header name)', hasImage: false },
  1040: { code: 1040, message: 'Invalid request rewrite (transformations disabled)', hasImage: false },
  1041: { code: 1041, message: 'Invalid request rewrite (header modification rejected)', hasImage: false },
  1101: { code: 1101, message: 'Worker threw a JavaScript exception', hasImage: false },
  1102: { code: 1102, message: 'Worker exceeded CPU time limit', hasImage: false },
  1104: { code: 1104, message: 'Email Address Obfuscation cannot be processed', hasImage: false },
  1105: { code: 1105, message: 'Rocket Loader exception', hasImage: false },
  1106: { code: 1106, message: 'Mirage exception', hasImage: false },
  1200: { code: 1200, message: 'Cache connection limit reached', hasImage: false },
  1201: { code: 1201, message: 'Origin returned malformed HTTP', hasImage: false },
};

module.exports = statuses;
