// This file is not on TypeScript so that it's reused in the Node scripts

// hasImage: false 表示在 public/images/<code>.jpg 没有专属图片，前端会回落到 0.jpg
// messageZh: 状态码的中文名称，在中文版页面中显示于英文名下方

const statuses = {
  100: { code: 100, message: 'Continue', messageZh: '继续', hasImage: true },
  101: { code: 101, message: 'Switching Protocols', messageZh: '切换协议', hasImage: true },
  102: { code: 102, message: 'Processing', messageZh: '处理中', hasImage: true },
  103: { code: 103, message: 'Early Hints', messageZh: '早期提示', hasImage: true },
  200: { code: 200, message: 'OK', messageZh: '成功', hasImage: true },
  201: { code: 201, message: 'Created', messageZh: '已创建', hasImage: true },
  202: { code: 202, message: 'Accepted', messageZh: '已接受', hasImage: true },
  203: { code: 203, message: 'Non-Authoritative Information', messageZh: '非权威信息', hasImage: true },
  204: { code: 204, message: 'No Content', messageZh: '无内容', hasImage: true },
  205: { code: 205, message: 'Reset Content', messageZh: '重置内容', hasImage: true },
  206: { code: 206, message: 'Partial Content', messageZh: '部分内容', hasImage: true },
  207: { code: 207, message: 'Multi-Status', messageZh: '多状态', hasImage: true },
  208: { code: 208, message: 'Already Reported', messageZh: '已报告', hasImage: true },
  214: { code: 214, message: 'Transformation Applied', messageZh: '已应用转换', hasImage: true },
  226: { code: 226, message: 'IM Used', messageZh: '已使用实例操作', hasImage: true },
  300: { code: 300, message: 'Multiple Choices', messageZh: '多种选择', hasImage: true },
  301: { code: 301, message: 'Moved Permanently', messageZh: '永久移动', hasImage: true },
  302: { code: 302, message: 'Found', messageZh: '临时移动', hasImage: true },
  303: { code: 303, message: 'See Other', messageZh: '查看其他', hasImage: true },
  304: { code: 304, message: 'Not Modified', messageZh: '未修改', hasImage: true },
  305: { code: 305, message: 'Use Proxy', messageZh: '使用代理', hasImage: true },
  307: { code: 307, message: 'Temporary Redirect', messageZh: '临时重定向', hasImage: true },
  308: { code: 308, message: 'Permanent Redirect', messageZh: '永久重定向', hasImage: true },
  400: { code: 400, message: 'Bad Request', messageZh: '错误请求', hasImage: true },
  401: { code: 401, message: 'Unauthorized', messageZh: '未授权', hasImage: true },
  402: { code: 402, message: 'Payment Required', messageZh: '需要付款', hasImage: true },
  403: { code: 403, message: 'Forbidden', messageZh: '禁止访问', hasImage: true },
  404: { code: 404, message: 'Not Found', messageZh: '未找到', hasImage: true },
  405: { code: 405, message: 'Method Not Allowed', messageZh: '方法不允许', hasImage: true },
  406: { code: 406, message: 'Not Acceptable', messageZh: '不可接受', hasImage: true },
  407: { code: 407, message: 'Proxy Authentication Required', messageZh: '需要代理身份验证', hasImage: true },
  408: { code: 408, message: 'Request Timeout', messageZh: '请求超时', hasImage: true },
  409: { code: 409, message: 'Conflict', messageZh: '冲突', hasImage: true },
  410: { code: 410, message: 'Gone', messageZh: '已删除', hasImage: true },
  411: { code: 411, message: 'Length Required', messageZh: '需要内容长度', hasImage: true },
  412: { code: 412, message: 'Precondition Failed', messageZh: '前提条件失败', hasImage: true },
  413: { code: 413, message: 'Payload Too Large', messageZh: '请求体过大', hasImage: true },
  414: { code: 414, message: 'Request-URI Too Long', messageZh: '请求 URI 过长', hasImage: true },
  415: { code: 415, message: 'Unsupported Media Type', messageZh: '不支持的媒体类型', hasImage: true },
  416: { code: 416, message: 'Request Range Not Satisfiable', messageZh: '请求范围不满足', hasImage: true },
  417: { code: 417, message: 'Expectation Failed', messageZh: '期望失败', hasImage: true },
  418: { code: 418, message: 'I\'m a teapot', messageZh: '我是茶壶', hasImage: true },
  419: { code: 419, message: 'Page Expired', messageZh: '页面已过期', hasImage: true },
  420: { code: 420, message: 'Enhance Your Calm', messageZh: '冷静一下', hasImage: true },
  421: { code: 421, message: 'Misdirected Request', messageZh: '请求方向错误', hasImage: true },
  422: { code: 422, message: 'Unprocessable Entity', messageZh: '无法处理的实体', hasImage: true },
  423: { code: 423, message: 'Locked', messageZh: '已锁定', hasImage: true },
  424: { code: 424, message: 'Failed Dependency', messageZh: '依赖失败', hasImage: true },
  425: { code: 425, message: 'Too Early', messageZh: '请求过早', hasImage: true },
  426: { code: 426, message: 'Upgrade Required', messageZh: '需要升级', hasImage: true },
  428: { code: 428, message: 'Precondition Required', messageZh: '需要前提条件', hasImage: true },
  429: { code: 429, message: 'Too Many Requests', messageZh: '请求过多', hasImage: true },
  431: { code: 431, message: 'Request Header Fields Too Large', messageZh: '请求头字段过大', hasImage: true },
  444: { code: 444, message: 'No Response', messageZh: '无响应', hasImage: true },
  // Nginx
  494: { code: 494, message: 'Request Header Too Large', messageZh: '请求头过大', hasImage: false },
  450: { code: 450, message: 'Blocked by Windows Parental Controls', messageZh: '被 Windows 家长控制拦截', hasImage: true },
  451: { code: 451, message: 'Unavailable For Legal Reasons', messageZh: '因法律原因不可用', hasImage: true },
  495: { code: 495, message: 'SSL Certificate Error', messageZh: 'SSL 证书错误', hasImage: true },
  496: { code: 496, message: 'SSL Certificate Required', messageZh: '需要 SSL 证书', hasImage: true },
  497: { code: 497, message: 'HTTP Request Sent to HTTPS Port', messageZh: 'HTTP 请求发送到 HTTPS 端口', hasImage: true },
  498: { code: 498, message: 'Token expired/invalid', messageZh: '令牌已过期或无效', hasImage: true },
  499: { code: 499, message: 'Client Closed Request', messageZh: '客户端关闭请求', hasImage: true },
  500: { code: 500, message: 'Internal Server Error', messageZh: '服务器内部错误', hasImage: true },
  501: { code: 501, message: 'Not Implemented', messageZh: '未实现', hasImage: true },
  502: { code: 502, message: 'Bad Gateway', messageZh: '网关错误', hasImage: true },
  503: { code: 503, message: 'Service Unavailable', messageZh: '服务不可用', hasImage: true },
  504: { code: 504, message: 'Gateway Timeout', messageZh: '网关超时', hasImage: true },
  // 标准但之前缺失
  505: { code: 505, message: 'HTTP Version Not Supported', messageZh: '不支持的 HTTP 版本', hasImage: false },
  506: { code: 506, message: 'Variant Also Negotiates', messageZh: '变体也在协商', hasImage: true },
  507: { code: 507, message: 'Insufficient Storage', messageZh: '存储空间不足', hasImage: true },
  508: { code: 508, message: 'Loop Detected', messageZh: '检测到循环', hasImage: true },
  509: { code: 509, message: 'Bandwidth Limit Exceeded', messageZh: '超出带宽限制', hasImage: true },
  510: { code: 510, message: 'Not Extended', messageZh: '未扩展', hasImage: true },
  511: { code: 511, message: 'Network Authentication Required', messageZh: '需要网络身份验证', hasImage: true },
  // Cloudflare 5xx 系列
  520: { code: 520, message: 'Web Server Returned an Unknown Error', messageZh: 'Web 服务器返回未知错误', hasImage: false },
  521: { code: 521, message: 'Web Server Is Down', messageZh: 'Web 服务器宕机', hasImage: true },
  522: { code: 522, message: 'Connection Timed Out', messageZh: '连接超时', hasImage: true },
  523: { code: 523, message: 'Origin Is Unreachable', messageZh: '源站不可达', hasImage: true },
  524: { code: 524, message: 'A Timeout Occurred', messageZh: '发生超时', hasImage: false },
  525: { code: 525, message: 'SSL Handshake Failed', messageZh: 'SSL 握手失败', hasImage: true },
  526: { code: 526, message: 'Invalid SSL Certificate', messageZh: 'SSL 证书无效', hasImage: false },
  527: { code: 527, message: 'Railgun Error', messageZh: 'Railgun 错误', hasImage: false },
  530: { code: 530, message: 'Site Frozen', messageZh: '站点已冻结', hasImage: true },
  599: { code: 599, message: 'Network Connect Timeout Error', messageZh: '网络连接超时错误', hasImage: true },
  // Cloudflare 1xxx 系列
  1000: { code: 1000, message: 'DNS points to prohibited IP', messageZh: 'DNS 指向禁止的 IP', hasImage: false },
  1001: { code: 1001, message: 'DNS resolution error', messageZh: 'DNS 解析错误', hasImage: false },
  1002: { code: 1002, message: 'DNS points to prohibited IP', messageZh: 'DNS 指向禁止的 IP', hasImage: false },
  1003: { code: 1003, message: 'Direct IP access not allowed', messageZh: '不允许直接 IP 访问', hasImage: false },
  1004: { code: 1004, message: 'Host not configured to serve web traffic', messageZh: '主机未配置为提供 Web 流量', hasImage: false },
  1005: { code: 1005, message: 'Access Denied (IP banned by origin)', messageZh: '访问被拒绝（IP 被源站封禁）', hasImage: false },
  1006: { code: 1006, message: 'Access Denied (IP banned)', messageZh: '访问被拒绝（IP 已封禁）', hasImage: false },
  1007: { code: 1007, message: 'Access Denied (Self-signed SSL prohibited)', messageZh: '访问被拒绝（禁止自签名 SSL）', hasImage: false },
  1008: { code: 1008, message: 'Access Denied (ASN banned)', messageZh: '访问被拒绝（ASN 已封禁）', hasImage: false },
  1010: { code: 1010, message: 'Access denied: Browser threat score too high', messageZh: '访问被拒绝：浏览器威胁评分过高', hasImage: false },
  1011: { code: 1011, message: 'Access denied (Hotlink protection)', messageZh: '访问被拒绝（防盗链保护）', hasImage: false },
  1012: { code: 1012, message: 'Access denied (Cloudflare app blocked)', messageZh: '访问被拒绝（Cloudflare 应用拦截）', hasImage: false },
  1013: { code: 1013, message: 'HTTP hostname and TLS SNI hostname mismatch', messageZh: 'HTTP 主机名与 TLS SNI 主机名不匹配', hasImage: false },
  1014: { code: 1014, message: 'CNAME cross-user banned', messageZh: 'CNAME 跨用户已封禁', hasImage: false },
  1015: { code: 1015, message: 'You are being rate limited', messageZh: '您正在被限速', hasImage: false },
  1016: { code: 1016, message: 'Origin DNS error', messageZh: '源站 DNS 错误', hasImage: false },
  1018: { code: 1018, message: 'Cannot find domain\'s settings', messageZh: '找不到域名设置', hasImage: false },
  1019: { code: 1019, message: 'Compute server error (Worker recursive call)', messageZh: '计算服务器错误（Worker 递归调用）', hasImage: false },
  1020: { code: 1020, message: 'Access denied (Cloudflare Firewall Rule)', messageZh: '访问被拒绝（Cloudflare 防火墙规则）', hasImage: false },
  1023: { code: 1023, message: 'Host not configured (Page Rules)', messageZh: '主机未配置（页面规则）', hasImage: false },
  1025: { code: 1025, message: 'Plan limit exceeded', messageZh: '超出套餐限制', hasImage: false },
  1027: { code: 1027, message: 'Account suspended', messageZh: '账户已暂停', hasImage: false },
  1033: { code: 1033, message: 'Argo Tunnel error: connection unavailable', messageZh: 'Argo 隧道错误：连接不可用', hasImage: false },
  1034: { code: 1034, message: 'Edge IP restricted', messageZh: '边缘 IP 受限', hasImage: false },
  1035: { code: 1035, message: 'Invalid request rewrite (invalid URI path)', messageZh: '无效的请求重写（URI 路径无效）', hasImage: false },
  1036: { code: 1036, message: 'Invalid request rewrite (max length exceeded)', messageZh: '无效的请求重写（超出最大长度）', hasImage: false },
  1037: { code: 1037, message: 'Invalid request rewrite (invalid header name)', messageZh: '无效的请求重写（头名称无效）', hasImage: false },
  1040: { code: 1040, message: 'Invalid request rewrite (transformations disabled)', messageZh: '无效的请求重写（转换已禁用）', hasImage: false },
  1041: { code: 1041, message: 'Invalid request rewrite (header modification rejected)', messageZh: '无效的请求重写（头修改被拒绝）', hasImage: false },
  1101: { code: 1101, message: 'Worker threw a JavaScript exception', messageZh: 'Worker 抛出 JavaScript 异常', hasImage: false },
  1102: { code: 1102, message: 'Worker exceeded CPU time limit', messageZh: 'Worker 超出 CPU 时间限制', hasImage: false },
  1104: { code: 1104, message: 'Email Address Obfuscation cannot be processed', messageZh: '邮件地址混淆无法处理', hasImage: false },
  1105: { code: 1105, message: 'Rocket Loader exception', messageZh: 'Rocket Loader 异常', hasImage: false },
  1106: { code: 1106, message: 'Mirage exception', messageZh: 'Mirage 异常', hasImage: false },
  1200: { code: 1200, message: 'Cache connection limit reached', messageZh: '缓存连接数已达上限', hasImage: false },
  1201: { code: 1201, message: 'Origin returned malformed HTTP', messageZh: '源站返回了格式错误的 HTTP', hasImage: false },
}

module.exports = statuses;
